# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-24 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gedung', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruang',
            fields=[
                ('ID_Ruang', models.CharField(max_length=20)),
                ('Ruangan', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('PJ_Ruang', models.CharField(max_length=50)),
                ('Gedung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gedung.Gedung')),
            ],
        ),
    ]
