# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-24 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('ID_Detail', models.CharField(max_length=100)),
                ('Kode_Barang', models.IntegerField(primary_key=True, serialize=False)),
                ('Nama_Barang', models.CharField(max_length=100)),
                ('Merk', models.CharField(max_length=100)),
                ('Stock', models.IntegerField()),
                ('BAP_Kedatangan', models.ImageField(upload_to='')),
            ],
        ),
    ]
