# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-24 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('NIP_NRK', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_depan', models.CharField(max_length=100)),
                ('nama_belakang', models.CharField(max_length=100)),
                ('Alamat', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('Telp', models.CharField(max_length=15)),
                ('Role', models.CharField(choices=[('Tendik', 'Tendik'), ('Mahasiswa', 'Mahasiswa'), ('Dosen', 'Dosen'), ('Pegawai', 'Pegawai')], max_length=100)),
            ],
        ),
    ]
