# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-24 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('ruang', '0001_initial'),
        ('gedung', '0001_initial'),
        ('barang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPeminjaman',
            fields=[
                ('ID_DetailPeminjaman', models.CharField(max_length=20)),
                ('No_Peminjaman', models.IntegerField(primary_key=True, serialize=False)),
                ('Nama_Pegawai', models.CharField(max_length=100)),
                ('Tgl_Pinjam', models.DateField()),
                ('Tgl_Kembali', models.DateField()),
                ('Berita_Acara_Peminjaman', models.FileField(upload_to='')),
                ('NIP_NRK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Pegawai')),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Pinjam', models.CharField(max_length=20)),
                ('Nama_Barang', models.CharField(max_length=20)),
                ('Jumlah', models.IntegerField()),
                ('Gedung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gedung.Gedung')),
                ('Kode_Barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barang.Barang')),
                ('No_Peminjaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peminjaman.DetailPeminjaman')),
                ('Ruang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruang.Ruang')),
            ],
        ),
    ]
