# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-24 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gedung',
            fields=[
                ('ID_Gedung', models.CharField(max_length=20)),
                ('Nama_Gedung', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('PJ_Gedung', models.CharField(max_length=50)),
            ],
        ),
    ]
